language: android
jdk: oraclejdk8
install: true
script:
  - scripts/run-tests-travis.sh

android:
  components:
    - platform-tools-28.0.2
    - tools
    - sys-img-armeabi-v7a-android-28
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.2"
